import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="layer-base min-h-full">
        <div className="app-shell relative isolate min-h-full">
          <div className="pointer-events-none absolute inset-0 z-0" aria-hidden />
          <div className="pointer-events-none absolute inset-0 z-10" aria-hidden />
          <div className="relative z-20 min-h-full">{children}</div>
        </div>
      </body>
    </html>
  );
}
